//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use super::sea_orm_active_enums::GameType;
use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq, Serialize, Deserialize)]
#[sea_orm(table_name = "game")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub time: DateTimeWithTimeZone,
    pub game_type: Option<GameType>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::game_to_team_result::Entity")]
    GameToTeamResult,
}

impl Related<super::game_to_team_result::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::GameToTeamResult.def()
    }
}

impl Related<super::team_result::Entity> for Entity {
    fn to() -> RelationDef {
        super::game_to_team_result::Relation::TeamResult.def()
    }
    fn via() -> Option<RelationDef> {
        Some(super::game_to_team_result::Relation::Game.def().rev())
    }
}

impl ActiveModelBehavior for ActiveModel {}
