//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0

pub use super::game::Entity as Game;
pub use super::game_to_team_result::Entity as GameToTeamResult;
pub use super::team_result::Entity as TeamResult;
pub use super::team_result_to_user::Entity as TeamResultToUser;
pub use super::user::Entity as User;
