//! `SeaORM` Entity, @generated by sea-orm-codegen 1.0.0-rc.5

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, EnumIter, DeriveActiveEnum, Serialize, Deserialize)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "game_type")]
pub enum GameType {
    #[sea_orm(string_value = "PickleBall")]
    PickleBall,
    #[sea_orm(string_value = "Pool")]
    Pool,
    #[sea_orm(string_value = "TableTennis")]
    TableTennis,
}
