# .gitea/workflows/build.yaml

name: Build Crate
run-name: Build

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        # TODO -> Change to actions/checkout@v3 once this is resolved https://github.com/actions/checkout/issues/1370
        uses: https://gitea.com/ScMi1/checkout@v1
      - name: Get rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal
          components: rustfmt, clippy
          override: true
      - name: Add wasm32 to cargo
        run: rustup target add wasm32-unknown-unknown
      - name: Cache rust
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
      - name: Install perseus
        uses: baptiste0928/cargo-install@v2
        with:
          crate: perseus-cli
      - name: Install npm
        uses: actions/setup-node@v3
        with:
          node-version: latest
      - name: Install sass
        run: npm install -g sass
      - name: Install tailwindcss via npm
        run: npm install -D tailwindcss
      - name: Compile css
        run: npm run build
        # TODO -> Remove wasm-opt-version once perseus is updated
      - name: Build the project
        run: perseus --wasm-opt-version version_118 deploy --verbose
      - name: Run clippy for server
        run: RUSTFLAGS="--cfg=engine" cargo clippy --all
      - name: Run clippy for frontend
        run: RUSTFLAGS="--cfg=client" cargo clippy --all
